[package]
name = "k8s"
version = "0.1.0"
authors = ["Diego Pontoriero <dpontor@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
tokio-core = "0.1"

[build-dependencies]
glob = "0.2"
protoc-rust = "1.*"
